export const creds = {
  awsBucket: 'samadhanerp',
  awsRegion: 'ap-south-1',
  awsAccessKey: 'AKIAZGRJKC5EP34PJHE7',
  awsSecretKey: '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',
};

export const projectVariables = {
  DEF_PCKDIARY_TRANSTYPE_SOURCE_REFNO: '1', // Source
  DEF_PCKDIARY_TRANSTYPE_SOURCE_REFNO_TXT: 'Source',
  DEF_PCKDIARY_TRANSTYPE_EXPENSES_REFNO: '2', // Expense
  DEF_PCKDIARY_TRANSTYPE_EXPENSES_REFNO_TXT: 'Expenses',

  DEF_PCKDIARY_ENTRYTYPE_SELF_REFNO: '1', // Self
  DEF_PCKDIARY_ENTRYTYPE_SELF_REFNO_TXT: 'Self',
  DEF_PCKDIARY_ENTRYTYPE_COMPANY_REFNO: '2', // Company
  DEF_PCKDIARY_ENTRYTYPE_COMPANY_REFNO_TXT: 'Company',

  DEF_PCKDIARY_MODE_Cash_REFNO: '1',
  DEF_PCKDIARY_MODE_Upi_REFNO: '2',
  DEF_PCKDIARY_MODE_Cheque_REFNO: '3',
  DEF_PCKDIARY_MODE_RtgsNeft_REFNO: '4',
  DEF_PCKDIARY_MODE_Card_REFNO: '5',

  DEF_PCKDIARY_CATEGORY_Bank_REFNO: '1',
  DEF_PCKDIARY_CATEGORY_Contacts_REFNO: '2',
  DEF_PCKDIARY_CATEGORY_HandLoan_REFNO: '4',
  DEF_PCKDIARY_CATEGORY_Clients_REFNO: '24',
  DEF_PCKDIARY_CATEGORY_Clients_REFNO_TXT: 'Amount collected from Client',
  DEF_PCKDIARY_CATEGORY_Branch_REFNO: '27',
  DEF_PCKDIARY_CATEGORY_Supplier_REFNO: '28',
  DEF_PCKDIARY_CATEGORY_Vendor_REFNO: '29',
  DEF_PCKDIARY_CATEGORY_FollowupCustomer_REFNO: '30',
  DEF_PCKDIARY_CATEGORY_Employee_REFNO: '31',

  DEF_PCKDIARY_SUBCATEGORY_CashWithdrawal_REFNO: '1',
  DEF_PCKDIARY_Dynamic_Expense_ClientAmountGivenToCompany_REFNO: '68',
  DEF_PCKDIARY_Dynamic_Expense_ClientAmountGivenToCompany_FlagText: 'ptc',
};

export const projectFixedDesignations = {
  DEF_COMPANYADMIN_DESIGNATION_REFNO: 1,
  DEF_BRANCHADMIN_DESIGNATION_REFNO: 2,
  DEF_PROJECTSUPERVISOR_DESIGNATION_REFNO: 6,
  DEF_PROJECTLABOURS_DESIGNATION_REFNO: 5,
  DEF_MARKETINGEXECUTIVE_DESIGNATION_REFNO: 11,
};

export const projectFixedLocationTypes = {
  DEF_HEADOFFICE_REFNO: 1,
  DEF_REGIONALOFFICE_REFNO: 2,
  DEF_BRANCHOFFICE_REFNO: 3,
  DEF_PRODUCTIONUNIT_REFNO: 4,
};

export const projectLoginTypes = {
  DEF_SUPERADMIN_GROUP_REFNO: 1,
  DEF_SUPERADMIN_GROUP_REFNO_TXT: 'Super Admin',
  DEF_APPADMIN_GROUP_REFNO: 2,
  DEF_APPADMIN_GROUP_REFNO_TXT: 'App Admin',
  DEF_GENERALUSER_GROUP_REFNO: 3,
  DEF_GENERALUSER_GROUP_REFNO_TXT: 'General User',
  DEF_DEALER_GROUP_REFNO: 4,
  DEF_DEALER_GROUP_REFNO_TXT: 'Dealer',
  DEF_CONTRACTOR_GROUP_REFNO: 5,
  DEF_CONTRACTOR_GROUP_REFNO_TXT: 'Contractor',
  DEF_MENUFACTURER_GROUP_REFNO: 6,
  DEF_MENUFACTURER_GROUP_REFNO_TXT: 'Menufacturer Incharge',
  DEF_EMPLOYEE_GROUP_REFNO: 7,
  DEF_EMPLOYEE_GROUP_REFNO_TXT: 'Employee',
  DEF_CLIENT_GROUP_REFNO: 8,
  DEF_CLIENT_GROUP_REFNO_TXT: 'Client',
  DEF_ARCHITECTCONSULTANT_GROUP_REFNO: 9,
  DEF_ARCHITECTCONSULTANT_GROUP_REFNO_TXT: 'Architect & Consultant(PMC)',
  DEF_PROJECTSUPERVISOR_GROUP_REFNO: 10,
  DEF_PROJECTSUPERVISOR_GROUP_REFNO_TXT: 'Project Supervisor',
  DEF_CONTRACTOR_BRANCHADMIN_GROUP_REFNO: 11,
  DEF_CONTRACTOR_BRANCHADMIN_GROUP_REFNO_TXT: 'Contractor Branch Admin',
  DEF_DEALER_BRANCHADMIN_GROUP_REFNO: 12,
  DEF_DEALER_BRANCHADMIN_GROUP_REFNO_TXT: 'Dealer Branch Admin',
  DEF_SUPPLIER_GROUP_REFNO: 13,
  DEF_SUPPLIER_GROUP_REFNO_TXT: 'Supplier',
  DEF_VENDOR_GROUP_REFNO: 14,
  DEF_VENDOR_GROUP_REFNO_TXT: 'Vendor',
};

export const companyPaymentVerification = {
  DEF_COMPANYSOURCE_VERIFY: 'CompanySourceVerify',
  DEF_COMPANYEXPENSES_VERIFY: 'CompanyExpensesVerify',
  DEF_VIEW_COMPANYPAYMENT: 'CompanyPayment',
};
